### PR TITLE
Raise warning and return None on invalid WKB/WKT instead of raising exception

### LINKED ISSUE #320: GEOS errors decoding WKB prevent reading from datasets with invalid geometries
Various tools are using WKB as a serialization format or transport format between different binary packages (e.g., reading from GDAL as WKB, then converting to geometries here).  The same is probably true for WKT.

If any of the WKB geometries are malformed, GEOS throws an error and the entire conversion fails.  This makes it challenging to work with 3rd-party datasets that have invalid geometries, since these first need to be converted to geometries before they can be filtered.

We can potentially get around this in one of 2 ways:
1. add a parameter to `from_wkb` that would allow invalid geometries to be returned as `None`, and raise a warning
2. always return invalid geometries as `None` and raise a warning.  This is simpler and the only API change is that it doesn't fail outright (which is likely undesirable here).

The user can then filter out the `None` geometries and continue with the remainder.

To be clear: for other areas where the user can actually control how geometries are constructed, it is totally appropriate to raise an exception.  It is only in cases of deserializing WKB / WKT that it would be better to gracefully handle such errors.

### PR DESCRIPTION
**Pull request by brendan-ward**
Resolves #320

For reasons stated in #320, it is problematic to raise exceptions when deserializing invalid geometries from formats such as WKB.  This provides a way to gracefully read those in, raise a warning, and allow the user to filter them out instead of failing hard.

This adds a new enum value `PGWARN_GEOS_EXCEPTION` which is used to raise the GEOS exception as a warning instead of an exception.

### CODE REVIEW

File: src/geos.h [hunk 1]
```diff
@@ -85,6 +86,9 @@ enum {
     case PGERR_EMPTY_GEOMETRY:                                                           \
       PyErr_SetString(PyExc_ValueError, "One of the Geometry inputs is empty.");         \
       break;                                                                             \
+    case PGWARN_GEOS_EXCEPTION:                                                          \
+      PyErr_WarnEx(PyExc_Warning, last_error, 0);                                        \
```
Comment (jorisvandenbossche) [inline src/geos.h:90]: We should probably prepend that last_error message to make the warning message clearer? (saying something about some values being invalid WKB and being replaced with None in the result)

**Comment by brendan-ward** [comment]
A couple things to consider:
* I'm not sure that `ignore_invalid` is the best name for this parameter.  Is there something better?
* WKT and WKB warning types are separate enum values now but this doesn't add much value.  These could be combined into a single enum value if we don't think these need to be kept separate.

**Review by caspervdw — CHANGES_REQUESTED** [review]
This looks good. Some thoughts about the keyword `ignore_invalid`:

I think it should be a string (like numpy does in `np.seterr` or pandas in `to_datetime`). In that way we can later on add more functionality without breaking the API. This can be done now easily by only allowing `raise` and `ignore`, and converting that to a bool to pass into the `lib.from_wkt`. Then our external API remains extensible. Then it is reasonable to rename it to:

- `errors` (like in pandas.to_datetime https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html
- `on_invalid`

The separation between WKT and WKB warnings is not necessary, but I am also not against it. We can always change it back.

**Comment by jorisvandenbossche** [comment]
+1 on making it a string option

> This can be done now easily by only allowing `raise` and `ignore`

We could maybe also further use the terminology of `np.seterr` and use "raise" and "warn", which keeps the possibility open to add a "ignore" (which would not show the warning)? 

About naming, I think I find `on_invalid` a bit more descriptive than `errors`.

**Comment by brendan-ward** [comment]
Latest changes make this a string parameter and add an `ignore` option.

File: pygeos/io.py [hunk 2]
```diff
@@ -172,37 +181,59 @@ def from_wkt(geometry, **kwargs):
     ----------
     geometry : str or array_like
         The WKT string(s) to convert.
+    on_invalid : str, one of {"raise", "warn", "ignore"} (default: "raise")
```
Comment (caspervdw) [inline pygeos/io.py:184]: From https://numpydoc.readthedocs.io/en/latest/format.html:

> When a parameter can only assume one of a fixed set of values, those values can be listed in braces, with the default appearing first:
> order : {'C', 'F', 'A'}
    Description of `order`.

```suggestion
    on_invalid : {"raise", "warn", "ignore"}
```

The default is also listed in the call signature, which is visible in the docs.

Also the markup of the list below is not ok, see https://pygeos--321.org.readthedocs.build/en/321/io.html#pygeos.io.from_wkb. You might want each line with a hyphens (not sure)

**Review by caspervdw — APPROVED** [review]
Looks good, one nitpick about the docstrings and then good to merge!

File: pygeos/io.py [hunk 3]
```diff
@@ -172,37 +181,59 @@ def from_wkt(geometry, **kwargs):
...
+        raise: an exception will be raised if WKT input geometries are invalid.
+        warn: a warning will be raised and invalid WKT geometries will be
+        returned as `None`.
+        ignore: invalid WKT geometries will be returned as `None` without a warning.
```
Comment (jorisvandenbossche) [inline pygeos/io.py:188]:
```suggestion
        - raise: an exception will be raised if WKT input geometries are invalid.
        - warn: a warning will be raised and invalid WKT geometries will be
          returned as `None`.
        - ignore: invalid WKT geometries will be returned as `None` without a warning.
```
